#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  bluetoothctl power on > /dev/null
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  bluetoothctl power off > /dev/null
fi

STATUS=$(bluetoothctl show | grep Powered | cut -d':' -f2 | tr -d ' ')

if [[ "${STATUS}" = "no" ]]; then
  echo "off"
  echo "off"
  echo ""
else
  echo "on"
  echo "on"
  echo ""
fi
