#!/bin/bash

updates=$(checkupdates)
if [[ "${updates}" -eq "" ]]; then
  echo 0
  exit
fi

count=$(echo "$updates" | wc -l)
if [[ "${count}" -gt 0 ]]; then
  if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    notify-send Packages "$updates" --icon=dialog-information
  fi
fi

echo ${count}
