#!/bin/bash

enabled() {
  xinput list-props "ELAN25B4:00 04F3:25B4" | grep "Device Enabled" | cut -d':' -f2 | grep 1 > /dev/null
}

echo -n "<span color='#eec3c3'></span>"

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  if enabled; then
    xinput disable "ELAN25B4:00 04F3:25B4"
  else
    xinput enable "ELAN25B4:00 04F3:25B4"
  fi
fi

if enabled; then
  echo "<span color='green'></span>"
else
  echo "<span color='red'></span>"
fi
