#!/bin/bash

enabled() {
  xinput list-props "ELAN Touchscreen" | grep "Device Enabled" | cut -d':' -f2 | grep 1 > /dev/null
}

echo -n "<span color='#eec3c3'>  </span>"

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  if enabled; then
    xinput disable "ELAN Touchscreen"
  else
    xinput enable "ELAN Touchscreen"
  fi
fi

if enabled; then
  echo "<span color='green'></span>"
else
  echo "<span color='red'></span>"
fi
